### ISSUE TITLE
Questions on Lyra

### ISSUE THREAD

**Issue by kaiduanx** [google/lyra#56]
First, kudos to Google Lyra team to open source this awesome technology!

Second, this post is not about issue about the project, I am writing this post to try to understand Lyra more.

1. What is the optimal sample rate?

I played the encoder and decoder with audio data of different sample rates, the audio data is from testdata directory in source code.

// 8khz sample rate audio
-rw-rw-r-- 1 kxie kxie 130604 Jul 28 13:40 8khz_sample_000000_decoded.wav
-rw-rw-r-- 1 kxie kxie   1530 Jul 28 13:38 8khz_sample_000000.lyra
-rw-rw-r-- 1 kxie kxie  65708 Jul 28 13:25 8khz_sample_000000.wav

// 16khz sample rate audio
-rw-rw-r-- 1 kxie kxie 241964 Jul 28 13:41 16khz_sample_000001_decoded.wav
-rw-rw-r-- 1 kxie kxie   2835 Jul 28 13:38 16khz_sample_000001.lyra
-rw-rw-r-- 1 kxie kxie 241992 Jul 28 13:25 16khz_sample_000001.wav

// 32khz sample rate audio
-rw-rw-r-- 1 kxie kxie 161324 Jul 28 13:42 32khz_sample_000002_decoded.wav
-rw-rw-r-- 1 kxie kxie   1890 Jul 28 13:38 32khz_sample_000002.lyra
-rw-rw-r-- 1 kxie kxie 324140 Jul 28 13:25 32khz_sample_000002.wav

// 48khz sample rate audio
-rw-rw-r-- 1 kxie kxie 212524 Jul 28 13:42 48khz_sample_000003_decoded.wav
-rw-rw-r-- 1 kxie kxie   2490 Jul 28 13:38 48khz_sample_000003.lyra
-rw-rw-r-- 1 kxie kxie 638252 Jul 28 13:26 48khz_sample_000003.wav

From above, you can see the following,

1) For 8khz sample rate audio,   the size of decoded audio is about 2 times of the size of the original audio.
2) For 16khz sample rate audio, the size of decoded audio is about same as the size of the original audio.
3) For 32khz sample rate audio, the size of decoded audio is about half of the size of the original audio.
4) For 48khz sample rate audio, the size of the decoded audio is about 1/3 of the size of the original audio.

So what is the optimal sample rate for input audio? Does that mean Lyra works best for audio of 8Khz sample rate?

2 Features are extracted from speech every 40ms and are then compressed for transmission at a bitrate of 3kbps. 

Does this mean we have to signal the ptime as 40 in SDP?

3 This trick, plus 64-bit ARM optimisations, enables Lyra to not only run on cloud servers, but also on-device on mid-range phones, such as Pixel phones, in real time (with a processing latency of 100ms)

Lyra encodes frame of 40 ms, and the processing delay is 100 ms, does this mean it will take at least 140 ms to hear the first word on the receiver side?

Kudos to Lyra team again.

/Kaiduan

**Comment by aluebs** [comment]
Kaiduan, thank you for your feedback and questions. Please see my answers below.

1. The size of the decoded audio is irrelevant to the bitrate, since they are wav files like the original. The size just changes because of the different sample rates. If the sample_rate_hz flag in [decoder_main](https://github.com/google/lyra/blob/main/decoder_main.cc) is left to the default value, the decoded audio will have a sample rate of 16kHz. This means that it has double the number of samples than the 8kHz original, about the same than the 16kHz original, half the number of samples than the 32kHz original and 1/3 for the 48kHz original. To evaluate Lyra's compression, it is much more interesting to look at the encoded ".lyra" files' sizes. And there, since Lyra has a bitrate of 3kbps regardless of the sample rate, the only important factor is the length of the file in seconds.

2. If you send one Lyra packet per RTP one, then yes, the ptime should be 40. You can also explore sending multiple Lyra packets per RTP one (maybe 2 or 3), which would obviously increase the corresponding ptime by multiples of 40. This is a trade-off between the tolerable delay and lower bitrate by reducing the header overhead.

3. The processing delay of 100ms already includes the 40ms needed to fill the initial buffer, so it would take 100ms to hear the first word on the receive end. Actually if you check the file delay using [encoder_main](https://github.com/google/lyra/blob/main/encoder_main.cc)) and [decoder_main](https://github.com/google/lyra/blob/main/decoder_main.cc)), you'll see a delay closer to 60ms, since that doesn't take the buffer filling into account (See issue #47 for example).

Please let us know if something wasn't clear.

**Comment by kaiduanx** [comment]
Thank you so much @aluebs , the answer is crystal clear.

**Comment by sergeevabc** [comment]
Consider supplementing the Lyra user's manual with the required input sampling rate, since the encoder does not like 44100 Hz as follows

``` console
$ encoder_main.exe --input_path in44100.wav --output_dir .
E20240311 12:46:48.982857   740 lyra_encoder.cc:49] INVALID_ARGUMENT: Sample rate 44100 Hz is not supported by codec.
E20240311 12:46:48.982857   740 encoder_main_lib.cc:53] Could not create lyra encoder.
E20240311 12:46:48.982857   740 encoder_main_lib.cc:116] Unable to encode features for file "in44100.wav"
E20240311 12:46:48.982857   740 encoder_main.cc:86] Failed to encode "in44100.wav"
```

Also, the number of channels… stereo is not welcome.

``` console
$ encoder_main.exe --input_path in48000.wav --output_dir .
E20240311 12:55:24.607020  1056 lyra_encoder.cc:49] INVALID_ARGUMENT: Number of channels 2 is not supported by codec. It needs to be 1.
E20240311 12:55:24.607020  1056 encoder_main_lib.cc:53] Could not create lyra encoder.
E20240311 12:55:24.607020  1056 encoder_main_lib.cc:116] Unable to encode features for file "in48000.wav"
E20240311 12:55:24.607020  1056 encoder_main.cc:86] Failed to encode "in48000.wav"
```

And what is `--enable_preprocessing` exactly?
