### ISSUE TITLE
Bazel Build: Tensorflow / 11b2812d64e49bab9b6c489f79067fc94e69db9f.zip / GET returned 404 Not Found

### ISSUE THREAD

**Issue by trholding** [google/lyra#91]
Warning due to missing file during Bazel Build

```WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/google/XNNPACK/archive/11b2812d64e49bab9b6c489f79067fc94e69db9f.zip failed: class java.io.FileNotFoundException GET returned 404 Not Found```

Visit: https://storage.googleapis.com/mirror.tensorflow.org/github.com/google/XNNPACK/archive/11b2812d64e49bab9b6c489f79067fc94e69db9f.zip

Message:
```
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Details>No such object: mirror.tensorflow.org/github.com/google/XNNPACK/archive/11b2812d64e49bab9b6c489f79067fc94e69db9f.zip</Details>
</Error>
````

Actual file is available here:
https://github.com/google/XNNPACK/archive/11b2812d64e49bab9b6c489f79067fc94e69db9f.zip

It's building, however I am unsure if it is safe to ignore this warning.

Please advise / fix. Thx.

**Comment by aluebs** [comment]
I personally don't see this warning. What platform are you building it from? Did you modify the WORKSPACE file at all?
If Lyra builds and runs, it is probably safe to ignore warning, since XNNPACK would be necessary to run the TFLite models as is. It would also be possible to run the Models without XNNPACK, by setting the flag to false in [SoundStream Encoder](https://github.com/google/lyra/blob/main/soundstream_encoder.cc#L39) and [LyraGAN Model](https://github.com/google/lyra/blob/main/lyra_gan_model.cc#L38).

**Comment by trholding** [comment]
@aluebs It built without problems. Didn't modify the workspace file.

I was building it on Arch Linux x86-64 (5.19.10-arch1-1 #1 SMP PREEMPT_DYNAMIC)

I get this message when I run lyra:

INFO: Created TensorFlow Lite XNNPACK delegate for CPU.

I guess everything is ok.

**Comment by aluebs** [comment]
That message is expected since XNNPACK is the default delegate we use for running the TFLite models.
